name: blog_web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  crypto: ^3.0.3
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  oktoast: ^3.4.0
  riverpod_annotation: ^2.3.5
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.9
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.10
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
